export { isArray } from './src/is-array'
export { isBoolean } from './src/is-boolean'
export { isFunction } from './src/is-function'
export { isObject } from './src/is-object'
export { isString } from './src/is-string'
