export { isArray } from './is-array'
export { isBoolean } from './is-boolean'
export { isFunction } from './is-function'
export { isObject } from './is-object'
export { isString } from './src/is-string'
