export * from './is-array'
export * from './is-boolean'
export * from './is-function'
export * from './is-object'
export * from './is-string'
export * from './is-number'
export * from './is-numeric'
export * from './is-nil'
